FROM ubuntu:noble

LABEL org.opencontainers.image.authors="Badr @pythops"

ENV TZ=Etc/UTC \
    DEBIAN_FRONTEND=noninteractive

# Jammy sources
RUN echo "" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Types: deb" >>/etc/apt/sources.list.d/ubuntu.sources && \
    echo "URIs: http://ports.ubuntu.com/ubuntu-ports/" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Suites: jammy" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Components: main universe restricted multiverse" >> /etc/apt/sources.list.d/ubuntu.sources && \
    echo "Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" >>/etc/apt/sources.list.d/ubuntu.sources

# Nvidia required packages
RUN apt update && apt install -y \
        libgles2 \
        libpangoft2-1.0-0 \
        libxkbcommon0 \
        libwayland-egl1 \
        libwayland-cursor0 \
        libunwind8 \
        libasound2t64 \
        libpixman-1-0 \
        libjpeg-turbo8 \
        libinput10 \
        libcairo2 \
        libncursesw6 \
        libdrm-common \
        libdrm2 \
        libegl-mesa0 \
        libegl1 \
        libegl1-mesa \
        libgtk-3-0 \
        libgstreamer1.0-0 \
        libgstreamer-plugins-bad1.0-0 \
        libffi7 \
        libvulkan1 \
        libpcre3 \
        libssl-dev \
        device-tree-compiler \
        bridge-utils \
        i2c-tools \
        iso-codes \
        wget \
        cpio \
        busybox \
        nvme-cli \
        libseat1 \
        efibootmgr

# Additional tools
RUN apt install -y \
        systemd \
        bash-completion \
        build-essential \
        pkg-config \
        btrfs-progs \
        ca-certificates \
        cmake \
        curl \
        dnsutils \
        gnupg2 \
        htop \
        iotop \
        isc-dhcp-client \
        iputils-ping \
        kmod \
        linux-firmware \
        locales \
        net-tools \
        netplan.io \
        pciutils \
        python3-dev \
        samba \
        ssh \
        sudo \
        udev \
        unzip \
        usbutils \
        neovim \
        wpasupplicant \
        parted \
        gdisk \
        fdisk \
        e2fsprogs \
        mtd-utils \
        python-is-python3 \
        git \
        gpgv1

# Add Nvidia specific repos
RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
RUN apt update

# Nvidia containers
RUN apt install -y \
        docker.io \
        sudo apt install docker-compose-v2 \
        libnvidia-container-tools \
        libnvidia-container1:arm64 \
        nvidia-container-toolkit-base \
        nvidia-container-toolkit \
        nvidia-docker2

# Configure Docker file with Nvidia's parameters
RUN nvidia-ctk runtime configure --runtime=docker

RUN wget -q https://github.com/pythops/tegratop/releases/latest/download/tegratop-linux-arm64 -O /usr/local/bin/tegratop && \
    chmod +x /usr/local/bin/tegratop

# Resize the rootfs
COPY scripts/resizerootfs.sh /usr/local/bin
COPY scripts/resizerootfs.service /lib/systemd/system

# Generate locales
RUN locale-gen en_US.UTF-8

# Network configuration
COPY config/netcfg.yaml /etc/netplan/netcfg.yaml

# Enable services at startuo
RUN systemctl enable resizerootfs.service && \
    systemctl enable systemd-timesyncd

# New user
# username: jetson
# password: jetson
RUN useradd \
        --create-home \
        -G sudo,video,audio \
        -p $(openssl passwd -6 jetson) \
        -s /bin/bash \
        jetson

# Add /usr/local/cuda/bin to the PATH
RUN echo "if [ -d \"/usr/local/cuda/bin\" ] ; then" >> /home/jetson/.profile  && \
    echo "  PATH=\"/usr/local/cuda/bin:\$PATH\"" >> /home/jetson/.profile  && \
    echo "fi" >> /home/jetson/.profile
